"""Optional real-workbook fixtures, located at test time.

ExcelPilot's own tests are self-contained: every fixture is generated by
``fixtures.workbooks`` and ``fixtures.vba``. A handful of tests additionally run
against **real** workbooks, because synthetic fixtures cannot establish that
openpyxl round-trips a file the size and complexity Excel actually produces — the
37,883 x 120 sheet with ~69,000 formulas is what justified the workbook-engine
decision ([ADR-0001](../docs/adr/0001-workbook-engine.md)).

Those real workbooks are **not** part of this repository. They are somebody's
business data, and a public project has no business shipping them or assuming
where they live. So they are discovered at test time, and every test that uses
one skips when it is not configured.

How to supply them
------------------

Point ``EXCELPILOT_REAL_WORKBOOKS`` at a directory containing a ``manifest.json``
that maps a **role** to a workbook path, relative to that directory::

    {
      "large":          "path/to/a-big-workbook.xlsx",
      "wide":           "path/to/a-wide-workbook.xlsx",
      "macro_extension":"path/to/a-macro-enabled.xlsm",
      "macro_project":  "path/to/a-macro-enabled.xlsm"
    }

Every role is optional. A role that is absent, or whose file does not exist,
makes its tests skip and nothing else. No test fails because a real workbook was
not provided.

The roles name a *property* a workbook must have, not a particular file, so the
same tests work with any collection. No workbook, filename, or filesystem
convention from any particular machine is encoded here.

    export EXCELPILOT_REAL_WORKBOOKS=~/my-workbooks
    uv run pytest -m slow
"""

from __future__ import annotations

import json
import os
from pathlib import Path

#: Environment variable naming the directory holding ``manifest.json``.
MANIFEST_ENV = "EXCELPILOT_REAL_WORKBOOKS"

#: The manifest file inside that directory.
MANIFEST_NAME = "manifest.json"

#: Every role, with the property the workbook it names is expected to have.
#:
#: The property is the point: it is what a test actually needs, and stating it
#: here means a test can skip with a reason that explains itself rather than
#: failing on a file that happens not to be the right shape.
ROLES: dict[str, str] = {
    "large": "a large workbook: many formulas, defined names, and real complexity",
    "wide": "a workbook with a very wide sheet (100+ columns)",
    "macro_extension": "a macro-enabled workbook (.xlsm), for extension handling",
    "macro_project": "a macro-enabled workbook containing a real VBA project",
}

_roles: dict[str, str] | None = None


def manifest() -> dict[str, str]:
    """Read and cache the role manifest. Empty when unconfigured or invalid.

    A malformed manifest is treated as no manifest rather than as an error: the
    real-workbook tests are optional, and a typo in someone's fixture setup must
    not fail the suite.
    """
    global _roles
    if _roles is not None:
        return _roles
    _roles = {}
    raw = os.environ.get(MANIFEST_ENV, "").strip()
    if not raw:
        return _roles
    path = Path(raw).expanduser() / MANIFEST_NAME
    try:
        loaded = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return _roles
    if isinstance(loaded, dict):
        _roles = {str(k): str(v) for k, v in loaded.items() if isinstance(v, str)}
    return _roles


def root() -> Path | None:
    """The configured fixture directory, or ``None``."""
    raw = os.environ.get(MANIFEST_ENV, "").strip()
    return Path(raw).expanduser() if raw else None


def workbook(role: str) -> Path | None:
    """Resolve a role to a workbook path, or ``None`` if it is not available.

    Returns ``None`` — rather than raising — for every unavailable case, so
    callers can express "skip if absent" without handling configuration errors.
    """
    if role not in ROLES:
        raise KeyError(f"unknown real-workbook role {role!r}; expected one of {sorted(ROLES)}")
    relative = manifest().get(role, "").strip()
    if not relative:
        return None
    base = root()
    if base is None:
        return None
    candidate = Path(relative).expanduser()
    if not candidate.is_absolute():
        candidate = base / candidate
    try:
        resolved = candidate.resolve()
    except (OSError, RuntimeError):
        return None
    return resolved if resolved.is_file() else None


def skip_reason(role: str) -> str:
    """Why a role is unavailable, phrased for a ``skipif`` reason."""
    if os.environ.get(MANIFEST_ENV, "").strip():
        return f"real-workbook role {role!r} is not in the {MANIFEST_ENV} manifest"
    return (
        f"no real workbooks configured; set {MANIFEST_ENV} to a directory containing a "
        f"{MANIFEST_NAME} (see fixtures/real.py)"
    )


__all__ = [
    "MANIFEST_ENV",
    "MANIFEST_NAME",
    "ROLES",
    "manifest",
    "root",
    "skip_reason",
    "workbook",
]
